#!/bin/bash

ROOT=$(cd $(dirname ${BASH_SOURCE[0]})/../ && pwd -P)
TESTCASE_ROOT=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd -P)

export XSCHED_POLICY=GBL
export XSCHED_AUTO_XQUEUE=ON
export XSCHED_AUTO_XQUEUE_PRIORITY=0
export XSCHED_AUTO_XQUEUE_LEVEL=1
export XSCHED_AUTO_XQUEUE_THRESHOLD=4
export XSCHED_AUTO_XQUEUE_BATCH_SIZE=2
export LD_LIBRARY_PATH=${ROOT}/sys/xsched/output/lib:$LD_LIBRARY_PATH

${TESTCASE_ROOT}/app
